version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
    container_name: mystagram_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    image: mystagram/backend
    container_name: backend
    volumes:
      - ./backend/src:/backend/src:ro
      - ./backend/prisma:/backend/prisma:ro
    networks:
      mystagram_network:
        aliases: [mystagram.backend]
      target: development
    ports:
      - '4200:4200'
      - '5555:5555'
    command: npm run start
    depends_on:
      - db
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: mystagram/frontend
    container_name: frontend
    volumes:
      - ./frontend/src:/frontend/src:ro
    networks:
      mystagram_network:
        aliases: [mystagram.frontend]
    ports:
      - '3000:3000'
    command: npm run start
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: mystagram_pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - '5050:80'
    depends_on:
      - db

networks:
  mystagram_network:
    driver: bridge