version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
    container_name: mystagram_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mystagram_backend
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./backend/src:/backend/src

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mystagram_frontend
    ports:
      - '80:80'
    volumes:
      - ./backend/src:/backend/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: mystagram_pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - '5050:80'
    depends_on:
      - db
